config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # resources :posts
  get '/posts', to: 'posts#index', as: :posts
  get '/posts/new', to: 'posts#new', as: :new_post
  get '/posts/:id', to: 'posts#show', as: :post
  post '/posts', to: 'posts#create'
  get '/posts/:id/edit', to: 'posts#edit', as: :edit_post
  patch '/posts/:id', to: 'posts#update'
  delete '/posts/:id', to: 'posts#delete'
  get '/categories/:category_id/posts', to: 'posts#index', as: :category_posts
  # get '/categories/:category_handle/posts', to: 'posts#index', as: :category_posts
  root to: 'posts#index'
  # root "articles#index"

  # resources :articles do
  #   resources :comments
  # end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/category.rb
class Category < ApplicationRecord
    has_many :posts, dependent: :nullify
  end

app/models/concerns/post.rb
  
class Post < ApplicationRecord
    belongs_to :category
  
    scope :ordered, -> { order(id: :desc) }
    scope :with_categories, -> { includes(:category) }
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/posts_controller.rb
class PostsController < ApplicationController
    def index
      # @posts = Post.all.ordered.with_categories
      # if params[:category_id]
      #   @posts = @posts.where(category_id: params[:category_id])
      # end
      if params[:category_id]
        @category = Category.find(params[:category_id])
        @posts = @category.posts.ordered.with_categories
      end
      @posts ||= Post.all.ordered.with_categories

      if params[:query].present?
        @posts = @posts.where('title LIKE ?',"%#{params[:query]}%")
      end
    end
  
    def show
      load_post
    end
  
    def new
      @post = Post.new
    end
  
    def create
      @post = Post.new(post_params)
      @post.save
      redirect_to @post
    end
  
    def edit
      load_post
    end
  
    def update
      load_post
      @post.update(post_params)
      redirect_to :post
    end
  
    def delete
      load_post
      @post.destroy
      redirect_to :posts
    end
  
    private
  
    def post_params
      params.require(:post).permit(:title, :text, :category_id)
    end
  
    def load_post
      @post = Post.find(params[:id])
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WEBKr</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/posts/_form.html.erb
<!--<div class="container">
<%= simple_form_for @post do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title,class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :text %>
      <%= f.text_area :text,class: "form-control" %>
    </div>
    <div class="form-group">
      <%# <%= f.label :category_id %>
      <%# <%= f.select :category_id, Category.all.map { |c| [c.name, c.id] } %>
      <%= f.association :category, collection: Category.order(:name), prompt: "Choose a Category"%>
    </div>
    <%= f.submit class: "btn btn-primary"%>
  <% end %>
</div>
  -->


  
  <!--<%= simple_form_for @post do |f| %>
  <%= f.input :title %>
  <%= f.text_area :text %>
  <%= f.select :category_id, Category.all.map { |c| [c.name, c.id]} %>
  <%= f.button :submit %>
  <% end %>-->


<div class="form1">
  <%= form_for @post do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="form-group">
      <%= f.label :text %>
      <%= f.text_area :text %>
    </div>
    <div class="form-group">
      <%= f.label :category_id %>
      <%= f.select :category_id, Category.all.map { |c| [c.name, c.id] } %>
    </div>
    <%= f.submit %>
  <% end %>
</div>

app/views/layouts/posts/edit.html.erb
  
<h1>Edit post "<%= @post.title %>"</h1>
<%= render partial: 'form' %>

app/views/layouts/posts/index.html.erb
<div class="mycontent">
<h1>
    <%= @category&.name || "All" %> posts
</h1>

<% if @category %>
<%= link_to "All posts", posts_path%>
<% end %>
<%= form_with  method: :get do |form| %>
  <%= form.label :query, "Search for:" %>
  <%= form.text_field :query,value: params[:query]%>
  <%= form.submit "Search" %>
<% end %>
<%= link_to "Create new post", new_post_path %>
<div class="posts-container">
  <% @posts.each do |post| %>
    <div class="post">

      <%= link_to post do %>
        <h3> <%= post.title %> </h3>
      <% end %>
      <!--<p> <%= post.category.name %> </p>-->
      <%= link_to post.category.name, category_posts_path(post.category) %>
      <%# <%= link_to post.category.name, category_posts_path(category_handle: post.category_handle) %>
      <p> <%= post.created_at %> </p>
      <p> <%= post.text %> </p>
    </div>
  <% end %>
</div>
</div>

app/views/layouts/posts/new.html.erb
<h1>New post</h1>
<%= render partial: 'form' %>

app/views/layouts/posts/show.html.erb
<div class="post">
<h1> <%= @post.title %> </h1>
<p> <%= @post.category.name %> </p>
<p> <%= @post.created_at %> </p>
<p> <%= @post.text %> </p>

  <div class="link-container">
  <%= link_to 'Edit', edit_post_path(@post.id) %>
  </div>
  <div class="link-container">
  <%=
    link_to 'Delete', post_path(@post.id), method: :delete,
      data: { confirm: "Are you sure?" }, remote: true
  %>
  </div>
  <div class="link-container">
  <%= link_to 'Back to posts', posts_path %>
  </div>
</div>